name: Maven Build and run Tests Jobs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build with Maven
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    # Build 
    - name: Build with Maven  
      run: mvn clean compile

  test:
      name: Run Maven Tests
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      # Run tests
      - name: Run tests
        run: mvn clean test
